name: profile
description: "Profile module to manage user information."
version: 0.0.1
environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  core:
    path: ../core
  auth:
    path: ../auth
  flutter:
    sdk: flutter
  # If needed later, networking and other deps can be added.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
