name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:
resolution: workspace
environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 5.9.0
  go_router: ^17.0.1
  equatable: ^2.0.7
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  connectivity_plus: ^7.0.0
  freezed: ^3.2.3
  fimber: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
